### ISSUE TITLE
www.ows.newegg.com is now checking user-agent...

### ISSUE THREAD

**Issue by dubyabee2** [bemasher/NeweggMobileAPI#3]
On july 11, 2014, the server started to check the user-agent was the mobile app.  Unfortunately I don't have time to upload a change request but by setting user agent to  "Newegg iPhone App / 4.1.2" using Nokogiri or Mechanize...you'll be back in service...for now.

Thank You,
wb

**Comment by bemasher** [comment]
Closed by #4
