### ISSUE TITLE
On July 30, 2014, Newegg has added additional authentication so only mobile app can communicate to the www.ows.newegg.com

### ISSUE THREAD

**Issue by dubyabee2** [bemasher/NeweggMobileAPI#5]
A few weeks ago I reported/corrected that the user-agent was now validated by the server. Newegg has once again changed their authentication.

I am doing my best to verify and find out what has changed.  The mobile client has not changed for iOS so it something missing in the request to server, possibly a cookie.  I will update as I find more information.  Currently I believe this repository is not functioning currently till  a solution found.

**Comment by pipe01** [comment]
I assume you haven't yet found any solution.

**Comment by bemasher** [comment]
I haven't touched this in years, so no.

**Comment by dubyabee2** [comment]
No I didn't, I ended up building a brute force scrape that has been stable for a while...I later helped a friend overcome some issues with the mobile api so it can be done, but didnt go back to this code, regards William Brown
